spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  messages:
    basename: i18n/messages
    cache-seconds: 0
    encoding: UTF-8
  resources:
    cache-period: 0
